### ISSUE TITLE
[suggestion] the naming of the APublicKey, APrivateKey parameters are not accurate 

### ISSUE THREAD

**Issue by edwinyzh** [gmurt/ksAws#3]
The Public/Private Key concepts belongs to the Asymmetric Encryption area.
For example:
`function CreateSes(APublicKey, APrivateKey: string; ARegion: TksAwsRegion): IksAwsSES`

The more suitable names should be 'access key' and 'access secret', according to the AWS documents.

**Comment by gmurt** [comment]
Changed the code to use Access/Secret key.  Just uploaded an update. Also includes a new PutObject for uploading files to S3.
