### ISSUE TITLE
How to send html email?

### ISSUE THREAD

**Issue by edwinyzh** [gmurt/ksAws#4]
Hello Graham,

I tried to send html email by adding html code such as `<a href="https://google.com/"></a>` to the email body, but after received it's shown as plain text.

Is there a way to send html emails? Thanks!

**Comment by gmurt** [comment]
I've updated the code to treat emails as HTML by default.  I've added a new parameter to the CreateSesMessage function although this has a default value of "true" so your code should not need any changes to use the new HTML support.

Note: <a href="https://google.com/"></a> will not appear to show anything in the email as there's no text between the >< tags.

**Comment by edwinyzh** [comment]
Thanks Graham, will try it later.
